language: ruby

cache: bundler

before_install:
  - gem update bundler

before_script:
  - bundle update

script:
  - bundle exec rspec

rvm:
  - 1.9.3-p484
  - 2.1.2
  - 2.2.2

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

matrix:
  exclude:
  - rvm: 1.9.3-p484
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 1.9.3-p484
    gemfile: gemfiles/rails_5.1.gemfile

  - rvm: 2.1.2
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5.1.gemfile

  - rvm: 2.2.2
    gemfile: gemfiles/rails_3.0.gemfile
  - rvm: 2.2.2
    gemfile: gemfiles/rails_3.1.gemfile
